# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eric Chen
header:           http:
url:              //ericjwdchen.org
paginate:         5
baseurl:          /
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen_org
  email:          eric@ericjwdchen.org

gems:
  - jekyll-sitemap

sass:
  style: :compressed
