# Dependencies
markdown: kramdown
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

pygments: true

# Permalinks
permalink:        pretty

# Setup
title:            ericjwdchen.org
url:              http://ericjwdchen.github.io
paginate:         5
baseurl:          /
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen
  email:          eric.jwd.chen@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ericjwdchen/ericjwdchen.github.io

gems:
  - jekyll-sitemap
  - pygments.rb

sass:
  style: :compressed
