# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Eric Chen
url:              //ericjwdchen.org
paginate:         5
baseurl:
header:           "http:"
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen_org
  email:          eric@ericjwdchen.org


sass:
  style: :compressed

variables:
  primary-color: "#bf1f49"
