# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Eric Chen
url: https://ericchen.cc
author:
  name: Eric Chen
  url: https://twitter.com/ericchen_cc

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag