# Dependencies
markdown: kramdown
pygments: true

# Permalinks
permalink:        pretty

# Setup
title:            ericjwdchen
tagline:          a high-functioning nerd
url:              http://ericjwdchen.github.io
paginate:         5
baseurl:          /
author:
  name:           Eric Chen
  url:            https://twitter.com/ericjwdchen
  email:          eric.jwd.chen@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ericjwdchen/ericjwdchen.github.io
