# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Eric Chen
url: https://ericjwdchen.org
paginate: 5
author:
  name: Eric Chen
  url: https://twitter.com/ericjwdchen_org
  email: eric@ericjwdchen.org

sass:
  style: :compressed

plugins:
  - jekyll-seo-tag